[package]
authors = ["Walther Chen <walther.chen@gmail.com>"]
description = "Cross-platform library for managing passwords"
homepage = "https://github.com/hwchen/keyring-rs.git"
keywords = ["password", "cross-platform", "keychain", "keyring"]
license = "MIT OR Apache-2.0"
name = "keyring"
repository = "https://github.com/hwchen/keyring-rs.git"
version = "0.6.1"

[target.'cfg(target_os = "macos")'.dependencies]
hex = "0.3.1"
security-framework = "0.3.0"

[target.'cfg(target_os = "linux")'.dependencies]
secret-service = "0.4.0"

[target.'cfg(target_os = "windows")'.dependencies]
byteorder = "1.2.1"
advapi32-sys = "0.2.0"
winapi = "0.2.5"

[dev-dependencies]
clap = "2.0.5"
rpassword = "2.0.0"
