[package]
name = "iospw"
version = "0.1.0"
edition = "2018"

[lib]
name = "iospw"
crate-type = ["staticlib"]

[dependencies]
keyring = { path = "../keyring" }
core-foundation = "0.9.2"

[dev-dependencies]
rand = "0.8.4"
serial_test = "0.5.1"
